#![allow(unused)]
use rand::Rng;
use std::{io, usize};


/*
Simple Russian Roulette game made in Rust
User tries to guess a number between 1 and 10;

If the number matches the death number which is randomly generated by rust, you get shot

Prepare to Die!!
By Cyndie

*/

fn main()-> io::Result<()> {
    let death_number = rand::thread_rng().gen_range(0..10);
    loop {
        println!("Welcome to Simple Russian Roullete Game!");
        println!("Choose a number between 1 and 10!!");

        let mut your_choice = String::new();

        let stdin = io::stdin();

        stdin.read_line(&mut your_choice)?;

        let your_choice: u32 = match your_choice.trim().parse() {
            Ok(num) => num,
            Err(_) => continue,
        };

        if your_choice < 1 || your_choice > 10 {
            println!("Please enter a number between 1 and 10!");
            continue;
        }

        if your_choice == death_number {
            println!("BANG! And you died! Sorry It wasn't your lucky day.");
            break;

        } else {
            println!("Phew! Safe for now. But not for long! ");
        }

    }

    Ok(())

}
